# Generated by Django 4.1.3 on 2022-11-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
