# Generated by Django 4.1 on 2022-11-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
