# Generated by Django 4.1.2 on 2022-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple choice'), ('checked-box', 'Checked box'), ('comment-box', 'Comment box')], default='--------', max_length=15),
        ),
    ]
