# Generated by Django 4.1 on 2022-10-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Multiple choice', 'Multiple choice'), ('Checked box', 'Checked box'), ('Comment box', 'Comment box')], default='Multiple choice', max_length=15),
        ),
    ]
