# Generated by Django 4.1 on 2022-10-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_question_id_alter_survey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='id',
            new_name='uuid',
        ),
    ]
